version: "3.8"
services:
  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=production
      - ENV_FILE_LOCATION=configfile
  mysql-server:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "barshopen"
      MYSQL_PASSWORD: "very_secret_secret"
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      - 3306:3306
    volumes:
      - my_db:/src/website

volumes:
  my_db:
