version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "barshopen"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 3306:3306
    volumes:
      - my_db:/src/website
volumes:
  my_db:
